### ISSUE TITLE
Running as root without --no-sandbox not supported

### ISSUE THREAD

**Issue by jprivillaso** [westy92/headless-chrome-alpine#2] opened 2018-01-29 19:09 UTC
Hi, 
I followed every step:
1. Build
2. Run

And I also added the --no-sanbox flag to the CMD inside the Dockerfile. 
However, despite of doing that, this error keep appearing

`Running as root without --no-sandbox is not supported`

I'm **not** running as a root user and I'm running on Mac and my docker version is Version 17.12.0-ce-mac46 (21698)
Do you have any idea? 

Thank you :)

**Comment by westy92** [comment] 2018-03-12 18:22
Turns out the cause was a trailing comma in the `CMD` array. This should now be fixed with the `--no-sandbox` option being added.

**Closed as completed by westy92** 2018-03-12 18:22 UTC
